version: '3.8'

services:

  postgres:
    image: 'postgres:14'
    container_name: "family_budget_db"
    restart: always
    environment:
      - POSTGRES_DB=family_budget
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
