version: '3.8'

services:

  postgres_db:
    image: 'postgres:14'
    container_name: "family_budget_db"
    restart: always
    environment:
      - POSTGRES_DB=family_budget
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack

  backend:
    build: .
    container_name: bot_backend
    restart: always
    environment:
      - DATABASE_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres_db
      - DB_PORT=5432
    depends_on:
      - postgres_db
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge

volumes:
  postgres_data:
    driver: local